version: "3.1"

services:
  db:
    container_name: db
    environment:
      POSTGRES_PASSWORD: postgres
    #image: postgres
    #image: postgres:alpine
    #image: timescale/timescaledb:latest-pg10
    image: timescale/timescaledb-postgis:latest-pg10
    restart: always
    ports:
      - 5433:5432

  core:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: core
    depends_on: 
      - db
    environment:
      - JAVA_OPTS="-Xms384m -Xmx384m"
    image: niledb/core
    links:
      - db
    ports:
      - 443:443
      - 80:80
      - 1883:1883
    restart: always
